version: "3.9"

services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./apps/web-app/dist:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api-stac
      - api-titiler

  api-stac:
    image: api-stac

  api-titiler:
    image: ghcr.io/developmentseed/titiler:latest

volumes:
  caddy_data:
  caddy_config:
