services:
  caddy:
    image: caddy:latest
    # Open ports required for web traffic and HTTPS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Copy over caddy file (read only)
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      # Copy over web app files (read only)
      # - ./apps/web-app/dist:/srv:ro
      # Not sure about these
      # - caddy_data:/data
      # - caddy_config:/config
    depends_on:
      - api-stac
      - api-titiler
      - web-app

  web-app:
    image: web-app

  api-stac:
    image: api-stac

  api-titiler:
    image: ghcr.io/developmentseed/titiler:latest

volumes:
  caddy_data:
  caddy_config:
