services:
  caddy:
    image: caddy:latest
    # Open ports required for web traffic and HTTPS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Copy over caddy file (read only)
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - api-stac
      - api-titiler
      - web-app

  web-app:
    image: jmswsc/web-app:latest

  api-stac:
    image: jmswsc/api-stac:latest

  api-titiler:
    image: ghcr.io/developmentseed/titiler:latest

volumes:
  caddy_data:
  caddy_config:
