[project]
name = "api-segmentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "supervision>=0.27.0",
    "timm>=1.0.24",
    "ultralytics-opencv-headless>=8.4.7",
    "uvicorn>=0.40.0",
]
